version: "3"

services:
 players: 
  build: ./players
  ports:
    - 5000:80
  volumes:
    - ./players:/app
 site:
  build: ./sites
  ports:
    - 5002:80
  depends_on:
    - players
  volumes:
    - ./sites:/src 

